:repo: desktop
:idprefix:
:hide-uri-scheme:
:numbered:
:max-width: 900px
:icons: font
:toc: macro
:toclevels: 4
ifdef::env-github,env-browser[:outfilesuffix: .asciidoc]
ifdef::env-github[]
:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :fire:
:caution-caption: :warning:
:warning-caption: :no_entry:
endif::[]

# Contributing to Shabad OS for Desktop

Thank you for your interest to participate in Shabad OS projects!

There are many ways for people to contribute, beyond writing code or programming, by: logging bugs, reporting issues, and creating suggestions. All of which can be done through link:https://github.com/ShabadOS/{repo}/issues/new[creating a ticket] in our issue tracker. See our readme for other ways to link:README.adoc#Contributing[Contribute] or give link:README.adoc#Feedback[Feedback].

This document is for developers or programmers that wish to write code and directly contribute to the source code of Shabad OS for Desktop.

toc::[id="toc"]

## Getting Started

If you wish to better understand how Shabad OS works or want to debug an issue: get the source, build it, and run it locally.

### Prerequisites

In order to download necessary tools, clone the repository, and install dependencies, you'll need network access.

You'll need the following:

* https://git-scm.com/[Git]
* https://nodejs.org/en/[Node.JS], x64, version `>= 12.x`

We currently use precompiled binaries. If we need to compile native Node modules in the future, we would include the following prerequisites. The following instructions are not required to build, run, package, or distribute Shabad OS for desktop.

.See prerequisites for compile tool chain
[%collapsible]
====
* https://www.python.org/downloads/release/python-2715/[Python], at least version 2.7 (version 3 is not supported)
+
NOTE: Windows users will automatically install Python 2.7 through installing `windows-build-tools` npm module (see below)
* A C/C++ compiler tool chain for your platform:
  
  ... Windows
    *** Start Powershell as Administrator.
    *** Run `npm install --global windows-build-tools --vs2015`. (Try the `--debug` flag or check https://github.com/felixrieseberg/windows-build-tools[Windows Build Tools] if you encounter any problems.)
    *** Restart your computer
+
WARNING: Make sure your profile path only contains ASCII letters, otherwise it can lead to node-gyp usage problems (https://github.com/nodejs/node-gyp/issues/297[nodejs/node-gyp issue #297])
+
NOTE: If you have Visual Studio 2019 installed, you may face issues when using the default version of `node-gyp`. You may need to follow the solutions in https://github.com/nodejs/node-gyp/issues/1747[nodejs/node-gyp issue #1747].
  
  ... macOS
    *** https://developer.apple.com/xcode/downloads/[Xcode] can be used to install Command Line Tools containing `gcc` and the related tool-chain containing `make`.
    *** Open a terminal and run `xcode-select --install`.
  
  ... Linux
    *** `make`, `pkg-config`, GCC or another compile tool-chain
    *** Building packages has not been tested, so requirements are unknown
====

### Build

Install and build all of the dependencies:

[source,shell]
----
cd desktop
npm i <1>
----
<1> installs dependencies for frontend and backend

### Run

To spin up the development servers, run `npm start`, which will launch a frontend server on https://localhost:3000[port `3000`], and a backend server on https://localhost:42425[port `42425`]. Any changes to the backend will result in the server restarting. A manual restart can be triggered by entering `rs` into the terminal.

To produce a tree-map of the bundle and look for potential bloat, run `npm run build` at least once, and then `npm run analyze`.

### Package

Electron-builder is used to generate binaries. Run `npm run pack` for the binaries to test on your platform, and `npm run dist` to build an installer. Run `npm run` or see `package.json` for a full list of commands. The production builds launch a frontend server on port `1699` and backend server port `42424`.

### Overview

The `app` folder contains the Electron wrapper, the backend Node application, and the frontend React application.

The frontend is using `create-react-app`, websockets for synchronizing clients, and API for search.

The backend is using proposed ES+ modules with the `esm` shim module.

## Workflow

The general workflow of development is to choose an issue to work on, create a feature branch off `dev` branch, and submit a pull request. This model is shared across all repos in the Shabad OS organization.

IMPORTANT: Please see the shared docs for Workflow (Issue Tracking, Branching, and Pull Requests) in the link:https://github.com/ShabadOS/.github/wiki/How-to-Contribute#workflow[How To Contribute wiki article].

## Coding Guidelines

Our coding guidelines are also (mostly) shared across all repos in the Shabad OS organization. Aside from scope definitions (which are repo specific), the rest should be referenced in the wiki article.

IMPORTANT: Please see the shared docs for Coding Guidelines (Names, Comments, Style, Linting, and Commit Messages) in the link:https://github.com/ShabadOS/.github/wiki/How-to-Contribute#coding-guidelines[How to Contribute wiki article].

### Scope (Part of link:https://github.com/ShabadOS/.github/wiki/How-to-Contribute#commit-messages[Commit Messages])

The scope should be the name of the npm package affected (as perceived by the person reading the changelog generated from commit messages). These are the supported scopes in Desktop:

- **backend**
- **frontend/controller**
- **frontend/overlay**
- **frontend/presenter**
- **frontend/settings**

There are currently a few exceptions to the "use package name" rule:

- *packaging*: used for changes to the npm package layout in all of our packages, e.g. public path changes, package.json changes done to all packages, d.ts file/format changes, changes to bundles, etc.
- *changelog*: used for updating the release notes in CHANGELOG.md
- *none/empty string*: useful for `style`, `test`, and `refactor` changes that are done across all packages (e.g. style: add missing semicolons) and for docs changes that are not related to a specific package (e.g. docs: fix typo in tutorial).

## Thank you!

Your contributions to open source, large or small, make great projects like this possible. Thank you for taking the time to participate in this project.
