export type ClientSettings = {
  display: {
    previousLines: number,
    nextLines: number,
    larivaarGurbani: boolean,
    larivaarAssist: boolean,
    syllabicWeights: boolean,
    syllableCount: boolean,
    englishTranslation: boolean,
    spanishTranslation: boolean,
    punjabiTranslation: boolean,
    englishTransliteration: boolean,
    hindiTransliteration: boolean,
    urduTransliteration: boolean,
    lineEnding: boolean,
  },
  layout: {
    controllerZoom: number,
    presenterFontSize: number,
    relativeGurmukhiFontSize: number,
    relativeEnglishFontSize: number,
    relativePunjabiFontSize: number,
    relativeHindiFontSize: number,
    relativeUrduFontSize: number,
    centerText: boolean,
    justifyText: boolean,
    inlineTransliteration: boolean,
    inlineColumnGuides: boolean,
    splitOnVishraam: boolean,
    spacing: 'space-around' | 'space-between' | 'space-evenly' | 'flex-start' | 'flex-end' | 'center',
  },
  theme: {
    themeName: 'Day',
    simpleGraphics: boolean,
    backgroundImage: boolean,
    highlightCurrentLine: boolean,
    dimNextAndPrevLines: boolean,
  },
  vishraams: {
    vishraamHeavy: boolean,
    vishraamMedium: boolean,
    vishraamLight: boolean,
    vishraamColors: boolean,
    vishraamCharacters: boolean,
  },
  sources: {},
  hotkeys: {},
  security: {
    displayAnalytics: boolean,
    private: boolean,
  },
  search: {
    resultTranslationLanguage: 'None' | 'English' | 'Spanish' | 'Punjabi',
    resultTransliterationLanguage: 'None' | 'Hindi' | 'Urdu' | 'English',
    showResultCitations: boolean,
    lineEnding: boolean,
  },
}
