export type ServerSettings = {
  version: string,
  system: {
    launchOnStartup: boolean,
    multipleDisplays: boolean,
    fullscreenOnLaunch: boolean,
    serverAnalytics: boolean,
    automaticUpdates: boolean,
    betaOptIn: boolean,
  },
  notifications: {
    connectionEvents: boolean,
    disconnectionEvents: boolean,
    downloadEvents: boolean,
    downloadedEvents: boolean,
  },
  overlay: {
    overlayName: string,
    larivaarGurbani: boolean,
    larivaarAssist: boolean,
    englishTranslation: boolean,
    spanishTranslation: boolean,
    punjabiTranslation: boolean,
    englishTransliteration: boolean,
    hindiTransliteration: boolean,
    urduTransliteration: boolean,
    lineEnding: boolean,
  },
  closedCaptions: {
    zoomApiToken: null | string,
    larivaarGurbani: boolean,
    englishTranslation: boolean,
    spanishTranslation: boolean,
    punjabiTranslation: boolean,
    englishTransliteration: boolean,
    hindiTransliteration: boolean,
    urduTransliteration: boolean,
    lineEnding: boolean,
  },
}
