/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './app/__root'
import { Route as SettingsRouteRouteImport } from './app/settings/route'
import { Route as PresenterRouteRouteImport } from './app/presenter/route'
import { Route as IndexRouteImport } from './app/index'
import { Route as SettingsIndexRouteImport } from './app/settings/index'
import { Route as PresenterControllerRouteRouteImport } from './app/presenter/controller/route'
import { Route as PresenterControllerIndexRouteImport } from './app/presenter/controller/index'
import { Route as SettingsServerCategoryRouteImport } from './app/settings/server/$category'
import { Route as SettingsClientCategoryRouteImport } from './app/settings/client/$category'
import { Route as SettingsToolsOverlayIndexRouteImport } from './app/settings/tools/overlay/index'
import { Route as SettingsToolsClosedCaptionsIndexRouteImport } from './app/settings/tools/closedCaptions/index'
import { Route as SettingsServerAboutIndexRouteImport } from './app/settings/server/about/index'
import { Route as SettingsClientSourcesIndexRouteImport } from './app/settings/client/sources/index'
import { Route as SettingsClientHotkeysIndexRouteImport } from './app/settings/client/hotkeys/index'
import { Route as PresenterControllerSearchIndexRouteImport } from './app/presenter/controller/search/index'
import { Route as PresenterControllerNavigatorIndexRouteImport } from './app/presenter/controller/navigator/index'
import { Route as PresenterControllerHistoryIndexRouteImport } from './app/presenter/controller/history/index'
import { Route as PresenterControllerBookmarksIndexRouteImport } from './app/presenter/controller/bookmarks/index'

const ScreenReaderIndexLazyRouteImport = createFileRoute('/screen-reader/')()
const OverlayIndexLazyRouteImport = createFileRoute('/overlay/')()

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PresenterRouteRoute = PresenterRouteRouteImport.update({
  id: '/presenter',
  path: '/presenter',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./app/presenter/route.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenReaderIndexLazyRoute = ScreenReaderIndexLazyRouteImport.update({
  id: '/screen-reader/',
  path: '/screen-reader/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./app/screen-reader/index.lazy').then((d) => d.Route),
)
const OverlayIndexLazyRoute = OverlayIndexLazyRouteImport.update({
  id: '/overlay/',
  path: '/overlay/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./app/overlay/index.lazy').then((d) => d.Route))
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const PresenterControllerRouteRoute =
  PresenterControllerRouteRouteImport.update({
    id: '/controller',
    path: '/controller',
    getParentRoute: () => PresenterRouteRoute,
  } as any)
const PresenterControllerIndexRoute =
  PresenterControllerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PresenterControllerRouteRoute,
  } as any)
const SettingsServerCategoryRoute = SettingsServerCategoryRouteImport.update({
  id: '/server/$category',
  path: '/server/$category',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsClientCategoryRoute = SettingsClientCategoryRouteImport.update({
  id: '/client/$category',
  path: '/client/$category',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsToolsOverlayIndexRoute =
  SettingsToolsOverlayIndexRouteImport.update({
    id: '/tools/overlay/',
    path: '/tools/overlay/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsToolsClosedCaptionsIndexRoute =
  SettingsToolsClosedCaptionsIndexRouteImport.update({
    id: '/tools/closedCaptions/',
    path: '/tools/closedCaptions/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsServerAboutIndexRoute =
  SettingsServerAboutIndexRouteImport.update({
    id: '/server/about/',
    path: '/server/about/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsClientSourcesIndexRoute =
  SettingsClientSourcesIndexRouteImport.update({
    id: '/client/sources/',
    path: '/client/sources/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsClientHotkeysIndexRoute =
  SettingsClientHotkeysIndexRouteImport.update({
    id: '/client/hotkeys/',
    path: '/client/hotkeys/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const PresenterControllerSearchIndexRoute =
  PresenterControllerSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => PresenterControllerRouteRoute,
  } as any)
const PresenterControllerNavigatorIndexRoute =
  PresenterControllerNavigatorIndexRouteImport.update({
    id: '/navigator/',
    path: '/navigator/',
    getParentRoute: () => PresenterControllerRouteRoute,
  } as any)
const PresenterControllerHistoryIndexRoute =
  PresenterControllerHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => PresenterControllerRouteRoute,
  } as any)
const PresenterControllerBookmarksIndexRoute =
  PresenterControllerBookmarksIndexRouteImport.update({
    id: '/bookmarks/',
    path: '/bookmarks/',
    getParentRoute: () => PresenterControllerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/presenter': typeof PresenterRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/presenter/controller': typeof PresenterControllerRouteRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/overlay': typeof OverlayIndexLazyRoute
  '/screen-reader': typeof ScreenReaderIndexLazyRoute
  '/settings/client/$category': typeof SettingsClientCategoryRoute
  '/settings/server/$category': typeof SettingsServerCategoryRoute
  '/presenter/controller/': typeof PresenterControllerIndexRoute
  '/presenter/controller/bookmarks': typeof PresenterControllerBookmarksIndexRoute
  '/presenter/controller/history': typeof PresenterControllerHistoryIndexRoute
  '/presenter/controller/navigator': typeof PresenterControllerNavigatorIndexRoute
  '/presenter/controller/search': typeof PresenterControllerSearchIndexRoute
  '/settings/client/hotkeys': typeof SettingsClientHotkeysIndexRoute
  '/settings/client/sources': typeof SettingsClientSourcesIndexRoute
  '/settings/server/about': typeof SettingsServerAboutIndexRoute
  '/settings/tools/closedCaptions': typeof SettingsToolsClosedCaptionsIndexRoute
  '/settings/tools/overlay': typeof SettingsToolsOverlayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/presenter': typeof PresenterRouteRouteWithChildren
  '/settings': typeof SettingsIndexRoute
  '/overlay': typeof OverlayIndexLazyRoute
  '/screen-reader': typeof ScreenReaderIndexLazyRoute
  '/settings/client/$category': typeof SettingsClientCategoryRoute
  '/settings/server/$category': typeof SettingsServerCategoryRoute
  '/presenter/controller': typeof PresenterControllerIndexRoute
  '/presenter/controller/bookmarks': typeof PresenterControllerBookmarksIndexRoute
  '/presenter/controller/history': typeof PresenterControllerHistoryIndexRoute
  '/presenter/controller/navigator': typeof PresenterControllerNavigatorIndexRoute
  '/presenter/controller/search': typeof PresenterControllerSearchIndexRoute
  '/settings/client/hotkeys': typeof SettingsClientHotkeysIndexRoute
  '/settings/client/sources': typeof SettingsClientSourcesIndexRoute
  '/settings/server/about': typeof SettingsServerAboutIndexRoute
  '/settings/tools/closedCaptions': typeof SettingsToolsClosedCaptionsIndexRoute
  '/settings/tools/overlay': typeof SettingsToolsOverlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/presenter': typeof PresenterRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/presenter/controller': typeof PresenterControllerRouteRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/overlay/': typeof OverlayIndexLazyRoute
  '/screen-reader/': typeof ScreenReaderIndexLazyRoute
  '/settings/client/$category': typeof SettingsClientCategoryRoute
  '/settings/server/$category': typeof SettingsServerCategoryRoute
  '/presenter/controller/': typeof PresenterControllerIndexRoute
  '/presenter/controller/bookmarks/': typeof PresenterControllerBookmarksIndexRoute
  '/presenter/controller/history/': typeof PresenterControllerHistoryIndexRoute
  '/presenter/controller/navigator/': typeof PresenterControllerNavigatorIndexRoute
  '/presenter/controller/search/': typeof PresenterControllerSearchIndexRoute
  '/settings/client/hotkeys/': typeof SettingsClientHotkeysIndexRoute
  '/settings/client/sources/': typeof SettingsClientSourcesIndexRoute
  '/settings/server/about/': typeof SettingsServerAboutIndexRoute
  '/settings/tools/closedCaptions/': typeof SettingsToolsClosedCaptionsIndexRoute
  '/settings/tools/overlay/': typeof SettingsToolsOverlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/presenter'
    | '/settings'
    | '/presenter/controller'
    | '/settings/'
    | '/overlay'
    | '/screen-reader'
    | '/settings/client/$category'
    | '/settings/server/$category'
    | '/presenter/controller/'
    | '/presenter/controller/bookmarks'
    | '/presenter/controller/history'
    | '/presenter/controller/navigator'
    | '/presenter/controller/search'
    | '/settings/client/hotkeys'
    | '/settings/client/sources'
    | '/settings/server/about'
    | '/settings/tools/closedCaptions'
    | '/settings/tools/overlay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/presenter'
    | '/settings'
    | '/overlay'
    | '/screen-reader'
    | '/settings/client/$category'
    | '/settings/server/$category'
    | '/presenter/controller'
    | '/presenter/controller/bookmarks'
    | '/presenter/controller/history'
    | '/presenter/controller/navigator'
    | '/presenter/controller/search'
    | '/settings/client/hotkeys'
    | '/settings/client/sources'
    | '/settings/server/about'
    | '/settings/tools/closedCaptions'
    | '/settings/tools/overlay'
  id:
    | '__root__'
    | '/'
    | '/presenter'
    | '/settings'
    | '/presenter/controller'
    | '/settings/'
    | '/overlay/'
    | '/screen-reader/'
    | '/settings/client/$category'
    | '/settings/server/$category'
    | '/presenter/controller/'
    | '/presenter/controller/bookmarks/'
    | '/presenter/controller/history/'
    | '/presenter/controller/navigator/'
    | '/presenter/controller/search/'
    | '/settings/client/hotkeys/'
    | '/settings/client/sources/'
    | '/settings/server/about/'
    | '/settings/tools/closedCaptions/'
    | '/settings/tools/overlay/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PresenterRouteRoute: typeof PresenterRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  OverlayIndexLazyRoute: typeof OverlayIndexLazyRoute
  ScreenReaderIndexLazyRoute: typeof ScreenReaderIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presenter': {
      id: '/presenter'
      path: '/presenter'
      fullPath: '/presenter'
      preLoaderRoute: typeof PresenterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-reader/': {
      id: '/screen-reader/'
      path: '/screen-reader'
      fullPath: '/screen-reader'
      preLoaderRoute: typeof ScreenReaderIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/': {
      id: '/overlay/'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof OverlayIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/presenter/controller': {
      id: '/presenter/controller'
      path: '/controller'
      fullPath: '/presenter/controller'
      preLoaderRoute: typeof PresenterControllerRouteRouteImport
      parentRoute: typeof PresenterRouteRoute
    }
    '/presenter/controller/': {
      id: '/presenter/controller/'
      path: '/'
      fullPath: '/presenter/controller/'
      preLoaderRoute: typeof PresenterControllerIndexRouteImport
      parentRoute: typeof PresenterControllerRouteRoute
    }
    '/settings/server/$category': {
      id: '/settings/server/$category'
      path: '/server/$category'
      fullPath: '/settings/server/$category'
      preLoaderRoute: typeof SettingsServerCategoryRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/client/$category': {
      id: '/settings/client/$category'
      path: '/client/$category'
      fullPath: '/settings/client/$category'
      preLoaderRoute: typeof SettingsClientCategoryRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/tools/overlay/': {
      id: '/settings/tools/overlay/'
      path: '/tools/overlay'
      fullPath: '/settings/tools/overlay'
      preLoaderRoute: typeof SettingsToolsOverlayIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/tools/closedCaptions/': {
      id: '/settings/tools/closedCaptions/'
      path: '/tools/closedCaptions'
      fullPath: '/settings/tools/closedCaptions'
      preLoaderRoute: typeof SettingsToolsClosedCaptionsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/server/about/': {
      id: '/settings/server/about/'
      path: '/server/about'
      fullPath: '/settings/server/about'
      preLoaderRoute: typeof SettingsServerAboutIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/client/sources/': {
      id: '/settings/client/sources/'
      path: '/client/sources'
      fullPath: '/settings/client/sources'
      preLoaderRoute: typeof SettingsClientSourcesIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/client/hotkeys/': {
      id: '/settings/client/hotkeys/'
      path: '/client/hotkeys'
      fullPath: '/settings/client/hotkeys'
      preLoaderRoute: typeof SettingsClientHotkeysIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/presenter/controller/search/': {
      id: '/presenter/controller/search/'
      path: '/search'
      fullPath: '/presenter/controller/search'
      preLoaderRoute: typeof PresenterControllerSearchIndexRouteImport
      parentRoute: typeof PresenterControllerRouteRoute
    }
    '/presenter/controller/navigator/': {
      id: '/presenter/controller/navigator/'
      path: '/navigator'
      fullPath: '/presenter/controller/navigator'
      preLoaderRoute: typeof PresenterControllerNavigatorIndexRouteImport
      parentRoute: typeof PresenterControllerRouteRoute
    }
    '/presenter/controller/history/': {
      id: '/presenter/controller/history/'
      path: '/history'
      fullPath: '/presenter/controller/history'
      preLoaderRoute: typeof PresenterControllerHistoryIndexRouteImport
      parentRoute: typeof PresenterControllerRouteRoute
    }
    '/presenter/controller/bookmarks/': {
      id: '/presenter/controller/bookmarks/'
      path: '/bookmarks'
      fullPath: '/presenter/controller/bookmarks'
      preLoaderRoute: typeof PresenterControllerBookmarksIndexRouteImport
      parentRoute: typeof PresenterControllerRouteRoute
    }
  }
}

interface PresenterControllerRouteRouteChildren {
  PresenterControllerIndexRoute: typeof PresenterControllerIndexRoute
  PresenterControllerBookmarksIndexRoute: typeof PresenterControllerBookmarksIndexRoute
  PresenterControllerHistoryIndexRoute: typeof PresenterControllerHistoryIndexRoute
  PresenterControllerNavigatorIndexRoute: typeof PresenterControllerNavigatorIndexRoute
  PresenterControllerSearchIndexRoute: typeof PresenterControllerSearchIndexRoute
}

const PresenterControllerRouteRouteChildren: PresenterControllerRouteRouteChildren =
  {
    PresenterControllerIndexRoute: PresenterControllerIndexRoute,
    PresenterControllerBookmarksIndexRoute:
      PresenterControllerBookmarksIndexRoute,
    PresenterControllerHistoryIndexRoute: PresenterControllerHistoryIndexRoute,
    PresenterControllerNavigatorIndexRoute:
      PresenterControllerNavigatorIndexRoute,
    PresenterControllerSearchIndexRoute: PresenterControllerSearchIndexRoute,
  }

const PresenterControllerRouteRouteWithChildren =
  PresenterControllerRouteRoute._addFileChildren(
    PresenterControllerRouteRouteChildren,
  )

interface PresenterRouteRouteChildren {
  PresenterControllerRouteRoute: typeof PresenterControllerRouteRouteWithChildren
}

const PresenterRouteRouteChildren: PresenterRouteRouteChildren = {
  PresenterControllerRouteRoute: PresenterControllerRouteRouteWithChildren,
}

const PresenterRouteRouteWithChildren = PresenterRouteRoute._addFileChildren(
  PresenterRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsClientCategoryRoute: typeof SettingsClientCategoryRoute
  SettingsServerCategoryRoute: typeof SettingsServerCategoryRoute
  SettingsClientHotkeysIndexRoute: typeof SettingsClientHotkeysIndexRoute
  SettingsClientSourcesIndexRoute: typeof SettingsClientSourcesIndexRoute
  SettingsServerAboutIndexRoute: typeof SettingsServerAboutIndexRoute
  SettingsToolsClosedCaptionsIndexRoute: typeof SettingsToolsClosedCaptionsIndexRoute
  SettingsToolsOverlayIndexRoute: typeof SettingsToolsOverlayIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsClientCategoryRoute: SettingsClientCategoryRoute,
  SettingsServerCategoryRoute: SettingsServerCategoryRoute,
  SettingsClientHotkeysIndexRoute: SettingsClientHotkeysIndexRoute,
  SettingsClientSourcesIndexRoute: SettingsClientSourcesIndexRoute,
  SettingsServerAboutIndexRoute: SettingsServerAboutIndexRoute,
  SettingsToolsClosedCaptionsIndexRoute: SettingsToolsClosedCaptionsIndexRoute,
  SettingsToolsOverlayIndexRoute: SettingsToolsOverlayIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PresenterRouteRoute: PresenterRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  OverlayIndexLazyRoute: OverlayIndexLazyRoute,
  ScreenReaderIndexLazyRoute: ScreenReaderIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
